services:
  app:
    restart: always
    build: .
    ports:
      - 7822:8080
    env_file:
      - path: .env
        required: false
    environment:
       - DATABASE_URL=postgresql://db:5432/db?user=user1&password=${POSTGRES_PASSWORD}
    volumes:
      - ./images:/images
  db:
    restart: always
    image: postgres:latest
    shm_size: 500mb
    ports:
      - 7422:5432
    env_file:
      - path: .env
        required: false
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_USER=user1
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
