services:
  db:
    restart: always
    image: postgres:latest
    shm_size: 500mb
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_USER=user1
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user1 -d db -p 5432 -h localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
volumes:
  db: